// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA614470ybU0G3qLRtE73qfjqmdQz7O_aM',
    appId: '1:452557147975:web:01cbf80aa2daace6564662',
    messagingSenderId: '452557147975',
    projectId: 'minisocialfeed',
    authDomain: 'minisocialfeed.firebaseapp.com',
    storageBucket: 'minisocialfeed.firebasestorage.app',
    measurementId: 'G-9XTN97TMDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD_UNVHwUkVSjw1E1mBoxbtGoqX1CYLgk',
    appId: '1:452557147975:android:9bb42c817b29bceb564662',
    messagingSenderId: '452557147975',
    projectId: 'minisocialfeed',
    storageBucket: 'minisocialfeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuUwLhdBGbTat4uh4C_LVvhEHJm5aN2s',
    appId: '1:452557147975:ios:9c7acae1a90794a0564662',
    messagingSenderId: '452557147975',
    projectId: 'minisocialfeed',
    storageBucket: 'minisocialfeed.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkuUwLhdBGbTat4uh4C_LVvhEHJm5aN2s',
    appId: '1:452557147975:ios:9c7acae1a90794a0564662',
    messagingSenderId: '452557147975',
    projectId: 'minisocialfeed',
    storageBucket: 'minisocialfeed.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialFeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA614470ybU0G3qLRtE73qfjqmdQz7O_aM',
    appId: '1:452557147975:web:3c7cf37a259b533b564662',
    messagingSenderId: '452557147975',
    projectId: 'minisocialfeed',
    authDomain: 'minisocialfeed.firebaseapp.com',
    storageBucket: 'minisocialfeed.firebasestorage.app',
    measurementId: 'G-0LSYSW20YK',
  );
}
